os: linux
dist: bionic
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgtest-dev
    - openmpi-bin
    - libopenmpi-dev
    - libnetcdf-c++4-dev

script:
- cd makefiles
- ./run_tests_ubuntu.sh
