language: cpp
os: linux
dist: bionic
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgtest-dev
    - openmpi-bin
    - libopenmpi-dev
    - libnetcdf-c++4-dev
    - cmake

before_install:
- cd /usr/src/gtest
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
- cd ${TRAVIS_BUILD_DIR}

script:
- cd makefiles
- ./run_tests_ubuntu.sh
