function [methodinfo,structs,enuminfo,ThunkLibName]=gatdaem1d_proto
%GATDAEM1D_PROTO Create structures to define interfaces found in 'gatdaem1d'.

%This function was generated by loadlibrary.m parser version  on Fri Jan 16 09:48:30 2026
%perl options:'gatdaem1d.i -outfile=gatdaem1d_proto.m -thunkfile=gatdaem1d_thunk_pcwin64.c -header=gatdaem1d.h'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival,'thunkname', ival);
MfilePath=fileparts(mfilename('fullpath'));
ThunkLibName=fullfile(MfilePath,'gatdaem1d_thunk_pcwin64');
% extern  int32_t __cdecl gatdaem1d_get_abi_version (); 
fcns.thunkname{fcnNum}='int32Thunk';fcns.name{fcnNum}='gatdaem1d_get_abi_version'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
% extern  const char * __cdecl gatdaem1d_get_last_error_string ( const gatdaem1d_status s ); 
fcns.thunkname{fcnNum}='cstringint32Thunk';fcns.name{fcnNum}='gatdaem1d_get_last_error_string'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='cstring'; fcns.RHS{fcnNum}={'int32'};fcnNum=fcnNum+1;
% extern  gatdaem1d_status __cdecl createhandle ( const char * systemfile , gatdaem1d_system_handle * ptr_handle ); 
fcns.thunkname{fcnNum}='int32cstringvoidPtrThunk';fcns.name{fcnNum}='createhandle'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'cstring', 'uint64Ptr'};fcnNum=fcnNum+1;
% extern  gatdaem1d_status __cdecl deletehandle ( gatdaem1d_system_handle * ptr_handle ); 
fcns.thunkname{fcnNum}='int32voidPtrThunk';fcns.name{fcnNum}='deletehandle'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'uint64Ptr'};fcnNum=fcnNum+1;
% extern  gatdaem1d_status __cdecl nsamplesperwaveform ( const gatdaem1d_system_handle handle , int32_t * n_samples ); 
fcns.thunkname{fcnNum}='int32uint64voidPtrThunk';fcns.name{fcnNum}='nsamplesperwaveform'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'uint64', 'int32Ptr'};fcnNum=fcnNum+1;
% extern  gatdaem1d_status __cdecl waveform ( const gatdaem1d_system_handle handle , double * time , double * currentwaveform , double * voltagewaveform ); 
fcns.thunkname{fcnNum}='int32uint64voidPtrvoidPtrvoidPtrThunk';fcns.name{fcnNum}='waveform'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'uint64', 'doublePtr', 'doublePtr', 'doublePtr'};fcnNum=fcnNum+1;
% extern  gatdaem1d_status __cdecl nwindows ( const gatdaem1d_system_handle handle , int32_t * n_windows ); 
fcns.thunkname{fcnNum}='int32uint64voidPtrThunk';fcns.name{fcnNum}='nwindows'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'uint64', 'int32Ptr'};fcnNum=fcnNum+1;
% extern  gatdaem1d_status __cdecl nturns ( const gatdaem1d_system_handle handle , int32_t * n_turns ); 
fcns.thunkname{fcnNum}='int32uint64voidPtrThunk';fcns.name{fcnNum}='nturns'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'uint64', 'int32Ptr'};fcnNum=fcnNum+1;
% extern  gatdaem1d_status __cdecl looparea ( const gatdaem1d_system_handle handle , double * loop_area ); 
fcns.thunkname{fcnNum}='int32uint64voidPtrThunk';fcns.name{fcnNum}='looparea'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'uint64', 'doublePtr'};fcnNum=fcnNum+1;
% extern  gatdaem1d_status __cdecl basefrequency ( const gatdaem1d_system_handle handle , double * base_frequency ); 
fcns.thunkname{fcnNum}='int32uint64voidPtrThunk';fcns.name{fcnNum}='basefrequency'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'uint64', 'doublePtr'};fcnNum=fcnNum+1;
% extern  gatdaem1d_status __cdecl peakcurrent ( const gatdaem1d_system_handle handle , double * peak_current ); 
fcns.thunkname{fcnNum}='int32uint64voidPtrThunk';fcns.name{fcnNum}='peakcurrent'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'uint64', 'doublePtr'};fcnNum=fcnNum+1;
% extern  gatdaem1d_status __cdecl windowtimes ( const gatdaem1d_system_handle handle , double * low , double * high ); 
fcns.thunkname{fcnNum}='int32uint64voidPtrvoidPtrThunk';fcns.name{fcnNum}='windowtimes'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'uint64', 'doublePtr', 'doublePtr'};fcnNum=fcnNum+1;
% extern  gatdaem1d_status __cdecl forwardmodel ( const gatdaem1d_system_handle handle , const gatdaem1d_system_geometry * pG , const gatdaem1d_earth * pE , gatdaem1d_response * pR ); 
fcns.thunkname{fcnNum}='int32uint64voidPtrvoidPtrvoidPtrThunk';fcns.name{fcnNum}='forwardmodel'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'uint64', 'gatdaem1d_system_geometryPtr', 'gatdaem1d_earthPtr', 'gatdaem1d_responsePtr'};fcnNum=fcnNum+1;
% extern  gatdaem1d_status __cdecl derivative ( const gatdaem1d_system_handle handle , const gatdaem1d_system_geometry * pG , const gatdaem1d_earth * pE , const char * dtype , int32_t dlayer , gatdaem1d_response * pR ); 
fcns.thunkname{fcnNum}='int32uint64voidPtrvoidPtrcstringint32voidPtrThunk';fcns.name{fcnNum}='derivative'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'uint64', 'gatdaem1d_system_geometryPtr', 'gatdaem1d_earthPtr', 'cstring', 'int32', 'gatdaem1d_responsePtr'};fcnNum=fcnNum+1;
% extern  gatdaem1d_status __cdecl fm_dlogc ( const gatdaem1d_system_handle handle , const gatdaem1d_system_geometry * pG , const gatdaem1d_earth * pE , double * output_buffer ); 
fcns.thunkname{fcnNum}='int32uint64voidPtrvoidPtrvoidPtrThunk';fcns.name{fcnNum}='fm_dlogc'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'uint64', 'gatdaem1d_system_geometryPtr', 'gatdaem1d_earthPtr', 'doublePtr'};fcnNum=fcnNum+1;
% extern  gatdaem1d_status __cdecl iptype_from_string ( const char * iptype_string , gatdaem1d_iptype * iptype ); 
fcns.thunkname{fcnNum}='int32cstringvoidPtrThunk';fcns.name{fcnNum}='iptype_from_string'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'cstring', 'int32Ptr'};fcnNum=fcnNum+1;
structs.gatdaem1d_system_geometry.members=struct('tx_height', 'double', 'tx_roll', 'double', 'tx_pitch', 'double', 'tx_yaw', 'double', 'txrx_dx', 'double', 'txrx_dy', 'double', 'txrx_dz', 'double', 'rx_roll', 'double', 'rx_pitch', 'double', 'rx_yaw', 'double');
structs.gatdaem1d_earth.members=struct('iptype', 'int32', 'nlayers', 'int32', 'thickness', 'doublePtr', 'conductivity', 'doublePtr', 'chargeability', 'doublePtr', 'timeconstant', 'doublePtr', 'frequencydependence', 'doublePtr');
structs.gatdaem1d_response.members=struct('nwindows', 'int32', 'PX', 'doublePtr', 'PY', 'doublePtr', 'PZ', 'doublePtr', 'SX', 'doublePtr', 'SY', 'doublePtr', 'SZ', 'doublePtr');
enuminfo.GATDAEM1D_IPTYPE=struct('GATDAEM1D_IPTYPE_NONE',0,'GATDAEM1D_IPTYPE_COLECOLE',1,'GATDAEM1D_IPTYPE_PELTON',2);
enuminfo.GATDAEM1D_STATUS=struct('GATDAEM1D_STATUS_OK',0,'GATDAEM1D_STATUS_ERRBADHANDLE',1,'GATDAEM1D_STATUS_ERRBADMAGIC',2,'GATDAEM1D_STATUS_ERRNULLSYS',3,'GATDAEM1D_STATUS_ERRCPPEXCEPTION',4);
enuminfo.GATDAEM1D_EXPECTED_ABI=struct('GATDAEM1D_EXPECTED_ABI_VERSION',100);
methodinfo=fcns;