set(PETSC_DIR $ENV{PETSC_DIR})
set(PETSC_INCLUDE_DIRS $ENV{PETSC_INCLUDE_DIRS})
set(PETSC_LIBRARY_DIR $ENV{PETSC_LIBRARY_DIR})
set(PETSC_LIBRARIES $ENV{PETSC_LIBRARIES})
set(PETSC_LINK_OPTIONS $ENV{PETSC_LINK_OPTIONS})

if (NOT EXISTS "${PETSC_DIR}")
	message(FATAL_ERROR "PETSC_DIR=${PETSC_DIR} does not exist")
	set(PETSC_FOUND FALSE)
endif()

if (NOT EXISTS "${PETSC_LIB_DIR}")
	message(FATAL_ERROR "PETSC_LIB_DIR=${PETSC_LIB_DIR} does not exist")
	set(PETSC_FOUND FALSE)
endif()

foreach(incdir ${PETSC_INCLUDE_DIRS})
	cmake_path(SET incdir NORMALIZE "${incdir}")
	if (NOT EXISTS "${incdir}")
		message(FATAL_ERROR "PETSc include directory ${incdir} does not exist")
		set(PETSC_FOUND FALSE)
	endif()
endforeach()

foreach(lib_name ${PETSC_LIBRARIES})
	set(full_lib_name ${PETSC_LIB_DIR}/${lib_name})
	cmake_path(SET full_lib_name NORMALIZE "${full_lib_name}")
	list(APPEND PETSC_LINK_LIBRARIES ${full_lib_name})
	if (NOT EXISTS "${full_lib_name}")
		message(FATAL_ERROR "PETSc library file ${full_lib_name} does not exist")
		set(PETSC_FOUND FALSE)
	endif()
endforeach()

set(PETSC_FOUND TRUE)
