message(STATUS "\nChecking for NETCDF C Library")
set(NETCDF_DIR  $ENV{NETCDF_DIR})
set(NETCDF_ROOT $ENV{NETCDF_DIR})

# On MSVC Import NetCDF C Library
if(MSVC)
	message(STATUS "Creating netcdf C import library")
	set(NETCDF_INCLUDE_DIRS ${NETCDF_DIR}/include)
	set(NETCDF_LIBRARY_DIRS ${NETCDF_DIR}/lib)
	set(NETCDF_LINK_LIBRARIES netcdf.lib)
	set(NETCDF_LINK_OPTIONS "")
	set(NETCDF_FOUND TRUE)
else()
	pkg_search_module(NETCDF REQUIRED IMPORTED_TARGET netcdf)
	if(NETCDF_FOUND)
		message(STATUS "NETCDF C libraries were found")
	else()
		message(STATUS "NETCDF C libraries were NOT found")
	endif()
endif()

if(NETCDF_FOUND)
	message(STATUS "Creating NETCDF::C INTERFACE")
	add_library(NETCDF::C INTERFACE IMPORTED)
	set_target_properties(NETCDF::C PROPERTIES
		INTERFACE_INCLUDE_DIRECTORIES "${NETCDF_INCLUDE_DIRS}"
		INTERFACE_LINK_DIRECTORIES "${NETCDF_LIBRARY_DIRS}"
		INTERFACE_LINK_LIBRARIES "${NETCDF_LINK_LIBRARIES}"
		INTERFACE_LINK_OPTIONS "${NETCDF_LINK_OPTIONS}"
	)
	reportvar(NETCDF_INCLUDE_DIRS)
	reportvar(NETCDF_LIBRARY_DIRS)
	reportvar(NETCDF_LINK_LIBRARIES)
	reportvar(NETCDF_LINK_OPTIONS)
endif()
